<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>

    <!-- SPRING BOOT -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.5</version>
        <relativePath/>
    </parent>

    <groupId>com.bookstore</groupId>
    <artifactId>BookStoreEcommerce</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>pom</packaging>

    <!-- SPRING CLOUD -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2023.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- MODULES -->
    <modules>
        <module>api-gateway</module>
        <module>eureka-server</module>
        <module>service/notification-service</module>
        <module>service/order-service</module>
        <module>service/cart-service</module>
        <module>service/product-service</module>
        <module>service/user-service</module>
        <module>service/customer-service</module>
        <module>service/wishlist-service</module>
        <module>service/admin-service</module>
        <module>service/user-service</module>
    </modules>

</project>