# ===============================
# Server Configuration
# ===============================

# Port on which Cart Service will run
server.port=8084

# Name of your microservice
# This name is used in Eureka and Feign Client communication
spring.application.name=cart-service


# ===============================
# Eureka (Service Discovery)
# ===============================

# URL of Eureka Server where this service will register itself
# After registration, other services can discover this service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# ===============================
# Database Configuration (PostgreSQL)
# ===============================

# JDBC URL to connect to your PostgreSQL database
# Format: jdbc:postgresql://host:port/database_name
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore_cart

# Database username
spring.datasource.username=postgres

# Database password
spring.datasource.password=postgre123


# ===============================
# JPA / Hibernate Configuration
# ===============================

# Automatically updates database schema based on your Entity classes
spring.jpa.hibernate.ddl-auto=update

# Shows SQL queries in console (useful for debugging)
spring.jpa.show-sql=true