spring.application.name=config-server
server.port=8888

# Local config (file system)
spring.cloud.config.server.native.search-locations=classpath:/config

# Enable native mode
spring.profiles.active=native

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka