server.port=8086

spring.datasource.url=jdbc:postgresql://postgres:5432/bookstore_customer
spring.datasource.username=postgres
spring.datasource.password=postgre123

spring.jpa.hibernate.ddl-auto=update